apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-server-deploy
  labels:
    app: my-api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api-server
  template:
    metadata:
      labels:
        app: my-api-server
    spec:
      containers:
      - name: my-api-server
        image: 
        ports:
        - containerPort: 8080
